# This file was generated by GoReleaser. DO NOT EDIT.
class Ced < Formula
  desc "CLI tool to generate chapters from mp3 file"
  homepage "https://github.com/takaishi/ced"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/takaishi/ced/releases/download/v0.0.1/ced_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "473e0013ec106e79b34012268f568c3b9f74cc8c2aec89b874197ece3a47b67e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/takaishi/ced/releases/download/v0.0.1/ced_0.0.1_Linux_x86_64.tar.gz"
    sha256 "9d2b10e72bc4afa3729a021d88dd5516779703bb9bbdb9f8b4cd2bc750aca0ae"
  end

  def install
    bin.install Dir['ced']
  end

  test do
    system "#{bin}/ced"
  end
end
