# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Csv2tbl < Formula
  desc "`csv2tbl` is tool to convert csv to table."
  homepage "https://github.com/takaishi/csv2tbl"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/takaishi/csv2tbl/releases/download/v0.0.2/csv2tbl_0.0.2_darwin_amd64.tar.gz"
      sha256 "9a185939f01c1a1ab7bee22666d61be07e472d36abb5b55c9861989aed930f4e"

      def install
        bin.install Dir['csv2tbl']
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/takaishi/csv2tbl/releases/download/v0.0.2/csv2tbl_0.0.2_darwin_arm64.tar.gz"
      sha256 "e570e9b032eccfe4cf04bc443e437af30944c0f5d2a465207cad60a81357e1f1"

      def install
        bin.install Dir['csv2tbl']
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/takaishi/csv2tbl/releases/download/v0.0.2/csv2tbl_0.0.2_linux_arm64.tar.gz"
      sha256 "d173caf3052b123bfaeaca990234b0762534c8c49f8d96fdaabb8cadf6026622"

      def install
        bin.install Dir['csv2tbl']
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/takaishi/csv2tbl/releases/download/v0.0.2/csv2tbl_0.0.2_linux_amd64.tar.gz"
      sha256 "cd7049cc0dac18c3edef36e763c61c00e088790fd0b83e544612c42e45b2bcc8"

      def install
        bin.install Dir['csv2tbl']
      end
    end
  end

  test do
    system "#{bin}/csv2tbl"
  end
end
