# This file was generated by GoReleaser. DO NOT EDIT.
class FishHistoryGc < Formula
  desc "CLI tool to Generate and insert markdown's table of contents"
  homepage "https://github.com/takaishi/fish-history-gc"
  version "0.0.6"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/takaishi/fish-history-gc/releases/download/v0.0.6/fish-history-gc_0.0.6_Darwin_x86_64.tar.gz"
    sha256 "01f425d165e716d9d9b906ba1c21e896ff3b9a328cd29452bf031fba96c28b13"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/takaishi/fish-history-gc/releases/download/v0.0.6/fish-history-gc_0.0.6_Linux_x86_64.tar.gz"
      sha256 "2251f27a819ee442843ed7985b9fb01b929f1c3d5f9cd7073448f63653ef63b9"
    end
  end

  def install
    bin.install Dir['fish-history-gc']
  end

  test do
    system "#{bin}/fish-history-gc"
  end
end
