# This file was generated by GoReleaser. DO NOT EDIT.
class FishHistoryGc < Formula
  desc "CLI tool to Generate and insert markdown's table of contents"
  homepage "https://github.com/takaishi/fish-history-gc"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/takaishi/fish-history-gc/releases/download/v0.0.2/fish-history-gc_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "b997b4ed9b9739a40c3592a95a0d9167e1ad10733a875d4463193b48197e0d58"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/takaishi/fish-history-gc/releases/download/v0.0.2/fish-history-gc_0.0.2_Linux_x86_64.tar.gz"
      sha256 "b43f5837ba0071a0cb7d5cdafbc651b042aae88207790d8f7125cbd7bc00225d"
    end
  end

  def install
    bin.install Dir['fish-history-gc']
  end

  test do
    system "#{bin}/fish-history-gc"
  end
end
