# This file was generated by GoReleaser. DO NOT EDIT.
class Myproject < Formula
  desc "CLI tool to Generate and insert markdown's table of contents"
  homepage "https://github.com/takaishi/fish-history-gc"
  version "0.0.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/takaishi/fish-history-gc/releases/download/v0.0.9/fish-history-gc_0.0.9_Darwin_x86_64.tar.gz"
    sha256 "6814ca6407297237187cfcdb67c4d8d7f2b400eaf01e1e049e6d9a4b189a7bfa"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/takaishi/fish-history-gc/releases/download/v0.0.9/fish-history-gc_0.0.9_Linux_x86_64.tar.gz"
      sha256 "32239688cbcbbc41314eefccf80f0714f84b57fa03974452df77372c3f8fc8a1"
    end
  end

  def install
    bin.install Dir['fish-history-gc']
  end

  test do
    system "#{bin}/fish-history-gc"
  end
end
