# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pfwd < Formula
  desc "SSH Port Forward Tool"
  homepage "https://github.com/takaishi/pfwd"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/takaishi/pfwd/releases/download/v0.0.1/pfwd_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "be0fb871ecb7eba42958dd6ae8252828b76fb551d481b5f0cac19206fcd6679c"

      def install
        bin.install Dir['pfwd']
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/takaishi/pfwd/releases/download/v0.0.1/pfwd_0.0.1_Darwin_arm64.tar.gz"
      sha256 "5f7bbbb6a0afb46e0679e4d2f9080257bc4108b7c1c4d4fa3e799f4de17f8bf5"

      def install
        bin.install Dir['pfwd']
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/takaishi/pfwd/releases/download/v0.0.1/pfwd_0.0.1_Linux_x86_64.tar.gz"
      sha256 "829867069f0f094606971ea27e177b59d80ba715431ebd86d4c4f529e9236a1a"

      def install
        bin.install Dir['pfwd']
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/takaishi/pfwd/releases/download/v0.0.1/pfwd_0.0.1_Linux_arm64.tar.gz"
      sha256 "566584c837b696d27187560bac623a925aeb0c2fc0ab4f82d5120f25a3461599"

      def install
        bin.install Dir['pfwd']
      end
    end
  end

  test do
    system "#{bin}/pfwd"
  end
end
