# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pfwd < Formula
  desc "SSH Port Forward Tool"
  homepage "https://github.com/takaishi/pfwd"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/takaishi/pfwd/releases/download/v0.0.1/pfwd_0.0.1_Darwin_arm64.tar.gz"
      sha256 "a622376443d3d024cb11b5aec7fa99433203d7817bae13135496888fa3da6674"

      def install
        bin.install Dir['pfwd']
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/takaishi/pfwd/releases/download/v0.0.1/pfwd_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "414e0ee9d7330be3f26298a84bc130375c2c0d8052211081596520813a31b3e8"

      def install
        bin.install Dir['pfwd']
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/takaishi/pfwd/releases/download/v0.0.1/pfwd_0.0.1_Linux_arm64.tar.gz"
      sha256 "ce9ac8e700fd16d1f96877e3178fee8d560d905211ae2901e966f7cd26843753"

      def install
        bin.install Dir['pfwd']
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/takaishi/pfwd/releases/download/v0.0.1/pfwd_0.0.1_Linux_x86_64.tar.gz"
      sha256 "cc63d8e4f8718a1ccd28acb6caf489efeb634e1516844e2aae8d79871f7894f0"

      def install
        bin.install Dir['pfwd']
      end
    end
  end

  test do
    system "#{bin}/pfwd"
  end
end
