# This file was generated by GoReleaser. DO NOT EDIT.
class VaultPki < Formula
  desc "CLI tool to Generate and insert markdown's table of contents"
  homepage "https://github.com/takaishi/mdtoc"
  url "https://github.com/takaishi/vault-pki/releases/download/0.0.12/vault-pki_0.0.12_Darwin_x86_64.tar.gz"
  version "0.0.12"
  sha256 "bf8eed6bfc9d4447fcf435b31fd0bd2d87fdafc3af7f39389933222a23b33f5c"

  def install
    bin.install Dir['vault-pki']
  end

  test do
    system "#{bin}/vault-pki"
  end
end
