# This file was generated by GoReleaser. DO NOT EDIT.
class VaultPki < Formula
  desc "CLI tool to Generate and insert markdown's table of contents"
  homepage "https://github.com/takaishi/mdtoc"
  url "https://github.com/takaishi/vault-pki/releases/download/0.0.7/vault-pki_0.0.7_Darwin_x86_64.tar.gz"
  version "0.0.7"
  sha256 "8d4ebc045440754eef10d4d2ef9c5cc4979b860dd277bd19b019f4acd39a2477"

  def install
    bin.install Dir['vault-pki']
  end

  test do
    system "#{bin}/vault-pki"
  end
end
