# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfclean" do
  desc "CLI tool to clean up unused Terraform states"
  homepage "https://github.com/takaishi/tfclean"
  version "0.0.11"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfclean"

  on_macos do
    on_intel do
      url "https://github.com/takaishi/tfclean/releases/download/v0.0.11/tfclean_Darwin_x86_64.tar.gz"
      sha256 "136f22a799180f737bc5c0e062ae2cf78ca612e0c4d403ce04760ccdfeada95a"
    end
    on_arm do
      url "https://github.com/takaishi/tfclean/releases/download/v0.0.11/tfclean_Darwin_arm64.tar.gz"
      sha256 "2eee2b1e0f68b5d8da7a4de539f3f76ce56fac5f893ba293c2a9a92abf2d63a7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/takaishi/tfclean/releases/download/v0.0.11/tfclean_Linux_x86_64.tar.gz"
      sha256 "bc58e9749f338c3723b763ee97e0cff404bdf0ba9b9eb2669d9ff00dd4c40865"
    end
    on_arm do
      url "https://github.com/takaishi/tfclean/releases/download/v0.0.11/tfclean_Linux_arm64.tar.gz"
      sha256 "8981457f9f074a0a8add4207fa2ecd8029133ffff3ad9bbb18b86ed3aef36037"
    end
  end

  # No zap stanza required
end
