# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfclean" do
  desc "CLI tool to clean up unused Terraform states"
  homepage "https://github.com/takaishi/tfclean"
  version "0.0.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfclean"

  on_macos do
    on_intel do
      url "https://github.com/takaishi/tfclean/releases/download/v0.0.12/tfclean_Darwin_x86_64.tar.gz"
      sha256 "5bd485cb9777c961c6d60d475f02486b97469e78aee962b4b0e85458f840a8b6"
    end
    on_arm do
      url "https://github.com/takaishi/tfclean/releases/download/v0.0.12/tfclean_Darwin_arm64.tar.gz"
      sha256 "c5c149679df6e019b79fd52c328117ea348752ee077f839423b43a55f9123b2c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/takaishi/tfclean/releases/download/v0.0.12/tfclean_Linux_x86_64.tar.gz"
      sha256 "42d58e2a884e2a9192b59da79b997162f575b739ca2890b813a6ac0f3439e066"
    end
    on_arm do
      url "https://github.com/takaishi/tfclean/releases/download/v0.0.12/tfclean_Linux_arm64.tar.gz"
      sha256 "24fdb80dbd2c810cb4ae343390da7e362741d14c1799756c63eea4bf4680841b"
    end
  end

  # No zap stanza required
end
