# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfclean" do
  desc "CLI tool to clean up unused Terraform states"
  homepage "https://github.com/takaishi/tfclean"
  version "0.0.16"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfclean"

  on_macos do
    on_intel do
      url "https://github.com/takaishi/tfclean/releases/download/v0.0.16/tfclean_Darwin_x86_64.tar.gz"
      sha256 "ac5e090fbdce068d2a5a4e36aba6369ed57301f8f1d9bf8a68d3e93f8c093061"
    end
    on_arm do
      url "https://github.com/takaishi/tfclean/releases/download/v0.0.16/tfclean_Darwin_arm64.tar.gz"
      sha256 "c60ccfb5e93d39c2905136bcb7d8e35c91160d8f4d1c1046d26aac5a1f93ba99"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/takaishi/tfclean/releases/download/v0.0.16/tfclean_Linux_x86_64.tar.gz"
      sha256 "81f2cc13fe4cc53d2629345fc03d28662d7f70dda69a377e392e8df7ada155be"
    end
    on_arm do
      url "https://github.com/takaishi/tfclean/releases/download/v0.0.16/tfclean_Linux_arm64.tar.gz"
      sha256 "2a710cce99bf7393772d80c7d77c3ee3b48d09b88a0dca307c9e867862cf9397"
    end
  end

  # No zap stanza required
end
